AGS_GLOBAL_EVOLUTION_PIPELINE = [

"AGS_ERP_V3_PRODUCTION_ERP_V1",

"AGS_AI_LAYER",
"AGS_AI_BUSINESS_ASSISTANT",
"AGS_AI_ANALYTICS_ENGINE",
"AGS_AI_DECISION_ENGINE",
"AGS_AI_AGENT_RUNTIME",

"AGS_AUTOMATION_ENGINE",
"AGS_WORKFLOW_AUTOMATION",
"AGS_PROCESS_ENGINE",
"AGS_BUSINESS_RULE_AUTOMATION",

"AGS_CLOUD_PLATFORM",
"AGS_MULTI_TENANT_CLOUD",
"AGS_DEPLOYMENT_ENGINE",
"AGS_MONITORING_PLATFORM",
"AGS_CLOUD_OPERATIONS",

"AGS_MARKETPLACE_ECOSYSTEM",
"AGS_MODULE_MARKETPLACE",
"AGS_PLUGIN_MARKETPLACE",
"AGS_TEMPLATE_MARKETPLACE",
"AGS_AGENT_MARKETPLACE",

"AGS_GLOBAL_ENTERPRISE_PLATFORM",
"AGS_GLOBAL_BUSINESS_NETWORK",
"AGS_ENTERPRISE_ECOSYSTEM"

]
