AGS_ERP_V3_ENTERPRISE_ROADMAP = [

"AGS_ERP_V3_PRODUCTION_MODULES_BUILD",

"AGS_ERP_V3_INTEGRATION_LAYER",

"AGS_ERP_V3_WORKFLOW_AUTOMATION",

"AGS_ERP_V3_AI_BUSINESS_ASSISTANT",

"AGS_ERP_V3_ADVANCED_ANALYTICS",

"AGS_ERP_V3_REPORTING_INTELLIGENCE",

"AGS_ERP_V3_MOBILE_PLATFORM",

"AGS_ERP_V3_API_PLATFORM",

"AGS_ERP_V3_MARKETPLACE_READY",

"AGS_ERP_V3_CLOUD_DEPLOYMENT",

"AGS_ERP_V3_ENTERPRISE_RELEASE_V1",


"AGS_PLATFORM_V1",

"AGS_ERP_V3_ENTERPRISE",

"AGS_CLOUD_PLATFORM",

"AGS_MARKETPLACE_ECOSYSTEM",

"AGS_GLOBAL_ENTERPRISE_PLATFORM"

]
