#!/usr/bin/env python3
"""AGS-STUDIO Gap Analysis Report - Inline Version"""
import os, sys
from pathlib import Path
from datetime import datetime

P22 = {"Development Workflow": ["ags/pipeline"], "Command Registry": ["ags/commands", "ags/plugins"], "Automation Rules": ["ags/updater", "night_build", "night_worker"], "Build Pipeline": ["ags/pipeline", "enterprise_builder/pipeline"], "Code Generation": ["enterprise_builder/generators", "ags/generator"], "Documentation": ["agents/documentation.py", "AGS-VAULT/00_INDEXES"], "Quality Gates": ["enterprise_builder/core/enterprise_validator.py", "enterprise_builder/core/production_guard.py"]}
P23 = {"Autonomous Planner": ["enterprise_builder/planner/enterprise_planner.py", "agents/master.py"], "Autonomous Executor": ["enterprise_builder/core/action_executor.py", "enterprise_builder/core/enterprise_actions.py"], "Autonomous Reviewer": ["enterprise_builder/core/enterprise_validator.py"], "Autonomous Fixer": ["enterprise_builder/healing/self_healing_engine.py", "enterprise_builder/core/repair_manager.py"], "Self Improvement": ["agents/master.py", "enterprise_builder/core/ai_activation.py"], "Knowledge Learning": ["ags/ai", "ags/ai/session"], "Project Memory": ["ags/ai/session", "AGS-VAULT/02_KNOWLEDGE"]}
P24 = {"Module Templates": ["templates"], "Business Rules": ["enterprise_builder/generators"], "Form Generator": ["enterprise_builder/generators/ui/form_generator.py"], "Report Generator": ["enterprise_builder/generators", "reports"], "Workflow Generator": ["enterprise_builder/generators/ui"], "API Generator": ["enterprise_builder/generators/code/controller_generator.py"], "Documentation Generator": ["agents/documentation.py"]}

def check(root, patterns):
    found, partial, missing = [], [], []
    for p in patterns:
        full = root / p
        if full.exists():
            if full.is_dir():
                py = list(full.rglob("*.py"))
                if len(py) >= 3: found.append(f"{p} ({len(py)} files)")
                elif py: partial.append(f"{p} ({len(py)} files)")
                else: partial.append(f"{p} (empty)")
            else: found.append(p)
        else: missing.append(p)
    return found, partial, missing

def score(f, p, m):
    total = len(f) + len(p) + len(m)
    if not total: return 0
    s = (len(f) + len(p) * 0.5) / total * 100
    return round(s, 1)

def phase(name, comps, root):
    lines = [f"## {name}", "", "| Component | Status | Score | Evidence |", "|---|---|---|---|"]
    total = 0
    for c, pats in comps.items():
        f, p, m = check(root, pats)
        s = score(f, p, m)
        total += s
        if not m: st, ev = "DONE", ", ".join(f + p)
        elif not f and not p: st, ev = "MISSING", ", ".join(m)
        else: st, ev = "PARTIAL", f"have={len(f)+len(p)}/{len(pats)} missing={m}"
        lines.append(f"| {c} | {st} | {s}% | {ev} |")
    avg = round(total / len(comps), 1)
    lines.append(f"\n**Average: {avg}%**")
    return "\n".join(lines), avg

root = Path(sys.argv[1]).resolve()
ts = datetime.now().strftime("%Y%m%d_%H%M%S")
print(f"Analyzing: {root}")
m22, s22 = phase("PHASE_022 - Dev OS", P22, root)
m23, s23 = phase("PHASE_023 - Autonomous", P23, root)
m24, s24 = phase("PHASE_024 - ERP Factory", P24, root)
overall = round((s22 + s23 + s24) / 3, 1)

report = f"""# AGS-STUDIO Gap Analysis

Date: {ts}

## Summary

| Phase | Score |
|---|---|
| PHASE_022 | {s22}% |
| PHASE_023 | {s23}% |
| PHASE_024 | {s24}% |
| **Overall** | **{overall}%** |

---

{m22}

---

{m23}

---

{m24}

---

*Generated by gap_analysis.py*
"""

out = root / "AGS-VAULT" / "reports" / f"gap_analysis_{ts}.md"
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text(report, encoding="utf-8")
print(f"\nPHASE_022: {s22}%")
print(f"PHASE_023: {s23}%")
print(f"PHASE_024: {s24}%")
print(f"OVERALL:   {overall}%")
print(f"Report: {out}")
