AGS_PLATFORM_BUILD_PIPELINE = [

"AGS_ERP_V3_PRODUCTION_ERP_V1",

"AI_LAYER_BUILD",
"AGS_AI_BUSINESS_ASSISTANT",
"AGS_AI_ANALYTICS_ENGINE",
"AGS_AI_DECISION_ENGINE",
"AGS_AI_AGENT_RUNTIME",

"AUTOMATION_ENGINE_BUILD",
"AGS_WORKFLOW_AUTOMATION_ENGINE",
"AGS_PROCESS_AUTOMATION_ENGINE",
"AGS_RULE_ENGINE",

"CLOUD_PLATFORM_BUILD",
"AGS_CLOUD_RUNTIME",
"AGS_MULTI_TENANT_ENGINE",
"AGS_DEPLOYMENT_SYSTEM",
"AGS_CLOUD_MONITORING",

"MARKETPLACE_ECOSYSTEM_BUILD",
"AGS_MODULE_MARKETPLACE",
"AGS_PLUGIN_MARKETPLACE",
"AGS_TEMPLATE_MARKETPLACE",
"AGS_AGENT_MARKETPLACE",

"GLOBAL_ENTERPRISE_PLATFORM_BUILD",
"AGS_GLOBAL_BUSINESS_PLATFORM",
"AGS_ENTERPRISE_OPERATIONS",
"AGS_GLOBAL_ECOSYSTEM"

]
