AGS_GLOBAL_ENTERPRISE_V1 = [

"AI_LAYER",
"AGS_AI_CORE",
"AGS_AI_ASSISTANT",
"AGS_AI_ANALYTICS",
"AGS_AI_DECISION_ENGINE",
"AGS_AI_AGENT_RUNTIME",

"AUTOMATION_ENGINE",
"AGS_WORKFLOW_ENGINE",
"AGS_PROCESS_AUTOMATION",
"AGS_RULE_ENGINE",
"AGS_AUTONOMOUS_OPERATIONS",

"CLOUD_PLATFORM",
"AGS_CLOUD_CORE",
"AGS_MULTI_TENANT_ENGINE",
"AGS_DEPLOYMENT_ENGINE",
"AGS_MONITORING_ENGINE",
"AGS_CLOUD_SECURITY",

"MARKETPLACE_ECOSYSTEM",
"AGS_MODULE_MARKETPLACE",
"AGS_PLUGIN_MARKETPLACE",
"AGS_TEMPLATE_MARKETPLACE",
"AGS_AGENT_MARKETPLACE",

"GLOBAL_ENTERPRISE_PLATFORM",
"AGS_GLOBAL_BUSINESS_PLATFORM",
"AGS_ENTERPRISE_OPERATING_LAYER",
"AGS_GLOBAL_ECOSYSTEM"

]
