AGS_GLOBAL_SCALE_ENGINE = [

"AGS_GLOBAL_ENTERPRISE_PLATFORM",

"SALES_ENGINE_CUSTOMER_ACQUISITION",
"AGS_SALES_PIPELINE",
"AGS_LEAD_GENERATION_ENGINE",
"AGS_CUSTOMER_RELATION_ENGINE",
"AGS_SALES_AUTOMATION",
"AGS_MARKET_INTELLIGENCE",

"CUSTOMER_ONBOARDING_TENANT_SETUP",
"AGS_CUSTOMER_PORTAL",
"AGS_TENANT_MANAGER",
"AGS_ENVIRONMENT_PROVISIONING",
"AGS_CONFIGURATION_MANAGER",
"AGS_DATA_IMPORT_ENGINE",
"AGS_ONBOARDING_AUTOMATION",

"PRODUCTION_DEPLOYMENT_OPERATIONS",
"AGS_PRODUCTION_RUNTIME",
"AGS_DEPLOYMENT_ORCHESTRATOR",
"AGS_RELEASE_MANAGEMENT",
"AGS_UPDATE_ENGINE",
"AGS_INFRASTRUCTURE_MONITORING",
"AGS_SECURITY_OPERATIONS",
"AGS_BACKUP_SYSTEM",

"SUPPORT_CENTER_CUSTOMER_SUCCESS",
"AGS_SUPPORT_PLATFORM",
"AGS_TICKETING_ENGINE",
"AGS_KNOWLEDGE_BASE",
"AGS_SERVICE_MANAGEMENT",
"AGS_CUSTOMER_HEALTH_SCORE",
"AGS_SUCCESS_ANALYTICS",

"SUBSCRIPTION_LICENSE_REVENUE_SYSTEM",
"AGS_SUBSCRIPTION_MANAGER",
"AGS_LICENSE_ENGINE",
"AGS_BILLING_PLATFORM",
"AGS_PAYMENT_SYSTEM",
"AGS_REVENUE_ANALYTICS",
"AGS_FINANCIAL_OPERATIONS",

"GLOBAL_MARKET_EXPANSION_ENGINE",
"AGS_GLOBAL_PARTNER_NETWORK",
"AGS_REGION_EXPANSION",
"AGS_MULTI_LANGUAGE_PLATFORM",
"AGS_GLOBAL_COMPLIANCE",
"AGS_ENTERPRISE_MARKETING",
"AGS_WORLDWIDE_SCALE_ENGINE"

]
