AGS_GLOBAL_SCALE_PIPELINE = [

"GLOBAL_ENTERPRISE_PLATFORM",

"CUSTOMER_PLATFORM",
"AGS_CUSTOMER_MANAGEMENT",
"AGS_CUSTOMER_PORTAL",
"AGS_CUSTOMER_ONBOARDING",
"AGS_CUSTOMER_SUPPORT",

"PRODUCTION_DEPLOYMENT",
"AGS_PRODUCTION_RUNTIME",
"AGS_RELEASE_ENGINE",
"AGS_DEPLOYMENT_AUTOMATION",
"AGS_MONITORING_SYSTEM",
"AGS_BACKUP_SYSTEM",
"AGS_SECURITY_OPERATIONS",

"REVENUE_ENGINE",
"AGS_SUBSCRIPTION_ENGINE",
"AGS_LICENSE_ENGINE",
"AGS_BILLING_SYSTEM",
"AGS_PAYMENT_INTEGRATION",
"AGS_REVENUE_ANALYTICS",

"GLOBAL_SCALE",
"AGS_GLOBAL_OPERATIONS",
"AGS_REGION_MANAGEMENT",
"AGS_PARTNER_NETWORK",
"AGS_ENTERPRISE_EXPANSION",
"AGS_PLATFORM_EVOLUTION"

]
