AGS_ERP_V3_PRODUCTION_ROADMAP = [

"AGS_ERP_V3_MODULE_SCREENS_IMPLEMENTATION",
"AGS_ERP_V3_CRUD_ENGINE_INTEGRATION",
"AGS_ERP_V3_DATABASE_PRODUCTION_CONNECTION",
"AGS_ERP_V3_AUTHENTICATION_USER_MANAGEMENT",
"AGS_ERP_V3_ROLE_PERMISSION_SYSTEM",

"AGS_ERP_V3_CRM_PRODUCTION_MODULE",
"AGS_ERP_V3_PROJECT_MANAGEMENT_MODULE",
"AGS_ERP_V3_SUPPLIERS_MANAGEMENT_MODULE",
"AGS_ERP_V3_INVENTORY_MODULE",
"AGS_ERP_V3_PURCHASING_MODULE",
"AGS_ERP_V3_QUOTATION_MODULE",
"AGS_ERP_V3_INVOICE_MODULE",
"AGS_ERP_V3_ACCOUNTING_MODULE",
"AGS_ERP_V3_HR_MODULE",
"AGS_ERP_V3_REPORTING_MODULE",

"AGS_ERP_V3_DOCUMENT_MANAGEMENT",
"AGS_ERP_V3_NOTIFICATION_ENGINE",
"AGS_ERP_V3_BACKUP_RECOVERY",
"AGS_ERP_V3_AUDIT_LOGGING_SYSTEM",

"AGS_ERP_V3_PRODUCTION_ERP_V1",

"AGS_AI_BUSINESS_ASSISTANT",
"AGS_WORKFLOW_AUTOMATION_PLATFORM",
"AGS_ANALYTICS_PLATFORM",
"AGS_MOBILE_PLATFORM",
"AGS_API_PLATFORM",

"AGS_CLOUD_PLATFORM",
"AGS_MARKETPLACE_ECOSYSTEM",
"AGS_GLOBAL_ENTERPRISE_PLATFORM"

]
