AGS_ENTERPRISE_OPERATIONS_PIPELINE = [

"AGS_GLOBAL_ENTERPRISE_PLATFORM",

"CUSTOMER_ACQUISITION",
"AGS_LEAD_MANAGEMENT",
"AGS_SALES_PIPELINE",
"AGS_CUSTOMER_CRM",
"AGS_MARKETING_ENGINE",

"CUSTOMER_ONBOARDING",
"AGS_CUSTOMER_REGISTRATION",
"AGS_TENANT_CREATION",
"AGS_CONFIGURATION_WIZARD",
"AGS_INITIAL_DATA_IMPORT",
"AGS_CUSTOMER_TRAINING_SYSTEM",

"PRODUCTION_DEPLOYMENT",
"AGS_PRODUCTION_ENVIRONMENT",
"AGS_RELEASE_MANAGEMENT",
"AGS_DEPLOYMENT_AUTOMATION",
"AGS_SYSTEM_MONITORING",
"AGS_SECURITY_LAYER",
"AGS_BACKUP_RECOVERY",

"OPERATIONS_SUPPORT",
"AGS_SUPPORT_CENTER",
"AGS_TICKET_SYSTEM",
"AGS_SERVICE_MANAGEMENT",
"AGS_HEALTH_MONITORING",
"AGS_CUSTOMER_SUCCESS_ENGINE",

"SUBSCRIPTION_LICENSE_REVENUE",
"AGS_SUBSCRIPTION_ENGINE",
"AGS_LICENSE_MANAGEMENT",
"AGS_BILLING_ENGINE",
"AGS_PAYMENT_SYSTEM",
"AGS_REVENUE_ANALYTICS",

"GLOBAL_EXPANSION",
"AGS_PARTNER_NETWORK",
"AGS_REGION_MANAGEMENT",
"AGS_MULTI_LANGUAGE_PLATFORM",
"AGS_GLOBAL_MARKET_ENGINE",
"AGS_ENTERPRISE_GROWTH_SYSTEM"

]
