from app.ai.autonomous.workers.file_creator_worker import FileCreatorWorker


class ModuleBuilderWorker:


    def __init__(self):

        self.file_creator = FileCreatorWorker()



    def normalize_module_name(self, text):

        import re


        remove_words = [
            "with",
            "and",
            "the",
            "for",
            "system",
            "module",
            "build",
            "create",
            "management",
            "erp",
        ]


        text = text.lower()


        for word in remove_words:
            text = text.replace(
                word,
                ""
            )


        text = re.sub(
            r"[^a-z0-9_ ]",
            "",
            text
        )


        text = "_".join(
            text.split()
        )


        return text[:60].strip("_") or "sample"



    def generate_files(self, module):

        return [

            {
                "path":
                f"generated/modules/{module}/models/{module}.py",

                "content":
                f'''"""
{module} model
Generated by AGS Autonomous Factory
"""

class {module.title().replace("_","")}:
    pass
'''
            },


            {
                "path":
                f"generated/modules/{module}/services/{module}_service.py",

                "content":
                f'''"""
{module} service
Generated by AGS Autonomous Factory
"""

class {module.title().replace("_","")}Service:

    def create(self,data):
        return data
'''
            },


            {
                "path":
                f"generated/modules/{module}/controllers/{module}_controller.py",

                "content":
                f'''"""
{module} controller
Generated by AGS Autonomous Factory
"""

class Controller:

    pass
'''
            },


            {
                "path":
                f"generated/modules/{module}/ui/{module}_page.py",

                "content":
                f'''"""
{module} UI
Generated by AGS Autonomous Factory
"""

class Page:

    pass
'''
            },


            {
                "path":
                f"generated/modules/{module}/tests/test_{module}.py",

                "content":
                f'''def test_{module}():
    assert True
'''
            }

        ]



    def execute(self, task):


        if isinstance(task, dict):

            request = task.get(
                "request",
                ""
            )

        else:

            request = getattr(
                task,
                "description",
                ""
            )


        module = self.normalize_module_name(
            request
        )


        files = self.generate_files(
            module
        )


        result = self.file_creator.execute(
            {
                "files": files
            }
        )


        return {

            "status":
            "completed",

            "agent":
            "MODULE_BUILDER_AGENT",

            "module":
            module,

            "files_created":
            result,

            "message":
            "Real module generated by AGS Autonomous Factory"

        }
