AGS_ERP_V3_PRODUCTION_PIPELINE = [

"PHASE_NEXT_11_5_DESKTOP_GUI_RUNTIME",

"PHASE_NEXT_12_CRUD_ENGINE_INTEGRATION",

"PHASE_NEXT_13_DATABASE_PRODUCTION_CONNECTION",

"PHASE_NEXT_14_AUTHENTICATION_USER_MANAGEMENT",

"PHASE_NEXT_15_ROLE_PERMISSION_SYSTEM",

"PHASE_NEXT_16_CRM_PRODUCTION_MODULE",

"PHASE_NEXT_17_PROJECT_MANAGEMENT_MODULE",

"PHASE_NEXT_18_SUPPLIERS_MANAGEMENT_MODULE",

"PHASE_NEXT_19_INVENTORY_MODULE",

"PHASE_NEXT_20_PURCHASING_MODULE",

"PHASE_NEXT_21_QUOTATION_MODULE",

"PHASE_NEXT_22_INVOICE_MODULE",

"PHASE_NEXT_23_ACCOUNTING_MODULE",

"PHASE_NEXT_24_HR_MODULE",

"PHASE_NEXT_25_REPORTING_MODULE",

"PHASE_NEXT_26_DOCUMENT_MANAGEMENT",

"PHASE_NEXT_27_NOTIFICATION_ENGINE",

"PHASE_NEXT_28_BACKUP_RECOVERY",

"PHASE_NEXT_29_AUDIT_LOGGING_SYSTEM",

"PHASE_NEXT_30_PRODUCTION_ERP_V1",


"AGS_AI_BUSINESS_ASSISTANT",

"AGS_WORKFLOW_AUTOMATION",

"AGS_ANALYTICS_PLATFORM",

"AGS_MOBILE_PLATFORM",

"AGS_API_PLATFORM",

"AGS_CLOUD_PLATFORM",

"AGS_MARKETPLACE_ECOSYSTEM",

"AGS_GLOBAL_ENTERPRISE_PLATFORM"

]
