AGS_GLOBAL_OPERATIONS_V1 = [

"AGS_GLOBAL_ENTERPRISE_PLATFORM",

"SALES_CUSTOMER_ACQUISITION",
"AGS_CRM_SALES_ENGINE",
"AGS_LEAD_MANAGEMENT",
"AGS_PIPELINE_MANAGEMENT",
"AGS_SALES_AUTOMATION",
"AGS_CUSTOMER_INTELLIGENCE",

"CUSTOMER_ONBOARDING_SYSTEM",
"AGS_CUSTOMER_REGISTRATION",
"AGS_TENANT_PROVISIONING",
"AGS_CONFIGURATION_ENGINE",
"AGS_DATA_MIGRATION_ENGINE",
"AGS_CUSTOMER_SETUP_AUTOMATION",
"AGS_TRAINING_CENTER",

"PRODUCTION_DEPLOYMENT_OPERATIONS",
"AGS_PRODUCTION_RUNTIME",
"AGS_DEPLOYMENT_PIPELINE",
"AGS_RELEASE_ENGINE",
"AGS_VERSION_MANAGER",
"AGS_SYSTEM_MONITORING",
"AGS_SECURITY_OPERATIONS",
"AGS_BACKUP_RECOVERY",

"SUPPORT_CUSTOMER_SUCCESS",
"AGS_SUPPORT_CENTER",
"AGS_HELPDESK_ENGINE",
"AGS_TICKET_MANAGEMENT",
"AGS_SERVICE_LEVEL_MANAGER",
"AGS_CUSTOMER_SUCCESS_ANALYTICS",
"AGS_FEEDBACK_ENGINE",

"SUBSCRIPTION_LICENSE_REVENUE",
"AGS_SUBSCRIPTION_PLATFORM",
"AGS_LICENSE_MANAGER",
"AGS_BILLING_ENGINE",
"AGS_INVOICE_REVENUE_ENGINE",
"AGS_PAYMENT_GATEWAY",
"AGS_FINANCIAL_ANALYTICS",

"GLOBAL_MARKET_EXPANSION",
"AGS_PARTNER_ECOSYSTEM",
"AGS_REGION_MANAGER",
"AGS_MULTI_LANGUAGE_ENGINE",
"AGS_GLOBAL_COMPLIANCE_LAYER",
"AGS_MARKET_EXPANSION_ENGINE",
"AGS_ENTERPRISE_GROWTH_PLATFORM"

]
