AGS_GLOBAL_ENTERPRISE_PATH = [

"AI_LAYER",
"AGS_AI_CORE_ENGINE",
"AGS_AI_ASSISTANT",
"AGS_AI_ANALYTICS_ENGINE",
"AGS_AI_DECISION_ENGINE",
"AGS_AI_AGENT_RUNTIME",

"AUTOMATION_ENGINE",
"AGS_WORKFLOW_AUTOMATION_ENGINE",
"AGS_PROCESS_AUTOMATION_ENGINE",
"AGS_BUSINESS_RULE_ENGINE",
"AGS_AUTONOMOUS_OPERATION_ENGINE",

"CLOUD_PLATFORM",
"AGS_CLOUD_RUNTIME",
"AGS_MULTI_TENANT_ENGINE",
"AGS_DEPLOYMENT_PLATFORM",
"AGS_CLOUD_MONITORING",
"AGS_CLOUD_SECURITY",

"MARKETPLACE_ECOSYSTEM",
"AGS_MODULE_MARKETPLACE",
"AGS_PLUGIN_MARKETPLACE",
"AGS_TEMPLATE_MARKETPLACE",
"AGS_AI_AGENT_MARKETPLACE",
"AGS_PARTNER_NETWORK",

"GLOBAL_ENTERPRISE_PLATFORM",
"AGS_GLOBAL_BUSINESS_PLATFORM",
"AGS_ENTERPRISE_OPERATING_SYSTEM",
"AGS_GLOBAL_ECOSYSTEM_NETWORK",
"AGS_AUTONOMOUS_ENTERPRISE_PLATFORM"

]
