AGS_ENTERPRISE_STACK = [

"AI_LAYER",
"AGS_AI_CORE_ENGINE",
"AGS_AI_ASSISTANT",
"AGS_AI_ANALYTICS_ENGINE",
"AGS_AI_DECISION_ENGINE",
"AGS_AI_AGENT_RUNTIME",

"AUTOMATION_ENGINE",
"AGS_WORKFLOW_ENGINE",
"AGS_PROCESS_AUTOMATION",
"AGS_BUSINESS_RULE_ENGINE",
"AGS_AUTONOMOUS_OPERATIONS",

"CLOUD_PLATFORM",
"AGS_CLOUD_RUNTIME",
"AGS_MULTI_TENANT_ARCHITECTURE",
"AGS_DEPLOYMENT_ENGINE",
"AGS_CLOUD_MONITORING",
"AGS_CLOUD_SECURITY",

"MARKETPLACE_ECOSYSTEM",
"AGS_MODULE_MARKETPLACE",
"AGS_PLUGIN_MARKETPLACE",
"AGS_TEMPLATE_MARKETPLACE",
"AGS_AGENT_MARKETPLACE",

"GLOBAL_ENTERPRISE_PLATFORM",
"AGS_GLOBAL_BUSINESS_PLATFORM",
"AGS_ENTERPRISE_OPERATING_LAYER",
"AGS_GLOBAL_ECOSYSTEM_NETWORK"

]
