AGS_ULTIMATE_BUILD_PIPELINE = [

"AI_LAYER_BUILD",
"AGS_AI_BUSINESS_ASSISTANT",
"AGS_AI_ENGINE",
"AGS_AI_ANALYTICS",
"AGS_AI_DECISION_SYSTEM",
"AGS_AI_AGENT_RUNTIME",

"AUTOMATION_ENGINE_BUILD",
"AGS_WORKFLOW_AUTOMATION",
"AGS_PROCESS_AUTOMATION",
"AGS_BUSINESS_RULE_ENGINE",
"AGS_AUTONOMOUS_OPERATIONS",

"CLOUD_PLATFORM_BUILD",
"AGS_CLOUD_RUNTIME",
"AGS_MULTI_TENANT_PLATFORM",
"AGS_DEPLOYMENT_ENGINE",
"AGS_MONITORING_SYSTEM",
"AGS_CLOUD_OPERATIONS",

"MARKETPLACE_ECOSYSTEM_BUILD",
"AGS_MODULE_STORE",
"AGS_PLUGIN_STORE",
"AGS_TEMPLATE_STORE",
"AGS_AI_AGENT_STORE",
"AGS_PARTNER_ECOSYSTEM",

"GLOBAL_ENTERPRISE_PLATFORM_BUILD",
"AGS_GLOBAL_BUSINESS_PLATFORM",
"AGS_ENTERPRISE_PLATFORM",
"AGS_GLOBAL_OPERATIONS",
"AGS_AUTONOMOUS_ENTERPRISE_ECOSYSTEM"

]
